name: {{ cookiecutter.conda_env_name }}
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip:
      - sqlacodegen
  - numpy
  - scipy
  - scikit-learn
  - PyYAML>=3.11
  - pandas>=0.24
  - numpy>=1.16
  - scipy>=1.2
  - scikit-learn>=0.20
  - matplotlib>=3.0
  - ipython>=7.1
  - SQLAlchemy>=1.3
  - psycopg2>=2.7
  - pyqt>=5.9
  - cookiecutter
